spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.port=8080
# JWT configuration
jwt.secret=${AUTH_SECRET}
jwt.expiration=3600000