@base_url = http://localhost:8080/api/account

GET {{base_url}}/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNzg3NzU5OTc2LCJleHAiOjE3ODc3NjM1NzZ9.uqjz6gbAsF6Y4ltA7miiCDZxFIvrk4q3Qgr9Z6Cgi2K0L2Za-rcnn3CNh2GnNsAK
###

GET {{base_url}}/myAccounts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNzg3NzU5OTc2LCJleHAiOjE3ODc3NjM1NzZ9.uqjz6gbAsF6Y4ltA7miiCDZxFIvrk4q3Qgr9Z6Cgi2K0L2Za-rcnn3CNh2GnNsAK

###

POST {{base_url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNzg3NzU5OTc2LCJleHAiOjE3ODc3NjM1NzZ9.uqjz6gbAsF6Y4ltA7miiCDZxFIvrk4q3Qgr9Z6Cgi2K0L2Za-rcnn3CNh2GnNsAK

{
     "subtype": "Savings"
}

###