@base_url = http://localhost:8080/api/budget

GET {{base_url}}/myBudgets HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNzg3ODQwMDUxLCJleHAiOjE3ODc4NDM2NTF9.pEGkRgD2usCb5Z-3WCQ703sn0T0BTlaydTcH4MFaGR332jlV7VqdFAtHQ_4Z3zz6
###
GET {{base_url}}/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNzg3ODQwMDUxLCJleHAiOjE3ODc4NDM2NTF9.pEGkRgD2usCb5Z-3WCQ703sn0T0BTlaydTcH4MFaGR332jlV7VqdFAtHQ_4Z3zz6
###
PUT {{base_url}}/edit/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNzg3ODQwMDUxLCJleHAiOjE3ODc4NDM2NTF9.pEGkRgD2usCb5Z-3WCQ703sn0T0BTlaydTcH4MFaGR332jlV7VqdFAtHQ_4Z3zz6

{
  "income": 5000
}

