@base_url = http://localhost:8080/api/connect/bank

POST {{base_url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNzg3NjgyNjg3LCJleHAiOjE3ODc2ODYyODd9.bMmS3lSN_1rHtEn51tjU8NYeVyomrKYak2qsBCxXLx7rvwZa8nAtJnWV9EEQ5evD

{
  "plaidItemId": "456",
  "accessToken": "token1",
  "institutionName": "US Bank"
}